alg_name: "KN"
model_name: "./hugging_cache/gpt-j-6B"
device: 0
model_parallel: false

lr_scale: 1.0
n_toks: 10
refine: false
batch_size: 20
steps: 20
adaptive_threshold: 0.1
p: 0.4

ppl_sentence_num: 50  # 1000, 10000
ppl_batch_size: 10